services:
  - type: web
    name: interviewbit-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_GENAI_API_KEY
        sync: false
